# Generated by Django 5.0.1 on 2026-05-15 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_shop_barber_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="is_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="bookings.shop",
            ),
        ),
    ]
